// Auto-generated from 繝励Λ繧､繝繝・・_繝励Ο繧ｸ繧ｧ繧ｯ繧ｿ繝ｼ荳隕ｧ.csv
// Generated at: 2026-07-08T15:54:36.200Z

export const PROJECTOR_DB: ProjectorModel[] = [
  {
    id: 'xgimi-b0fr97kllq',
    brand: 'XGIMI',
    name: 'HORIZON 20 Standard Kit',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0FR97KLLQ.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0FR97KLLQ',
    resolution: '4K (3840x2160)',
    brightness: '3200ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0FR97KLLQ',
    priceJPY: 289900,
    salePriceJPY: 229900,
    discountPercent: 2070,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'xgimi-b0fr997ztp',
    brand: 'XGIMI',
    name: 'HORIZON 20 Pro Standard Kit',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0FR997ZTP.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0FR997ZTP',
    resolution: '4K (3840x2160)',
    brightness: '4100ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0FR997ZTP',
    priceJPY: 349900,
    salePriceJPY: 269900,
    discountPercent: 2290,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'xgimi-b0fr8d725m',
    brand: 'XGIMI',
    name: 'HORIZON 20 Max Standard Kit',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0FR8D725M.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0FR8D725M',
    resolution: '4K (3840x2160)',
    brightness: '',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0FR8D725M',
    priceJPY: 450900,
    salePriceJPY: 399900,
    discountPercent: 1130,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'xgimi-b095cf4lkv',
    brand: 'XGIMI',
    name: 'HORIZON Pro',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B095CF4LKV.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B095CF4LKV',
    resolution: '4K (3840x2160)',
    brightness: '1500ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Android TV 10.0',
    amazonASIN: 'B095CF4LKV',
    priceJPY: 197890,
    salePriceJPY: 119800,
    discountPercent: 3950,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'xgimi-b0gjbzbzw8',
    brand: 'XGIMI',
    name: 'TITAN',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0GJBZBZW8.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0GJBZBZW8',
    resolution: '4K (3840x2160)',
    brightness: '5000ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝・Η繧｢繝ｫ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'OS髱槫・阡ｵ(螟紋ｻ倥￠Google TV繝・ヰ繧､繧ｹ)',
    amazonASIN: 'B0GJBZBZW8',
    priceJPY: 698000,
    salePriceJPY: 598000,
    discountPercent: 1430,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'xgimi-b0d7pkhgwy',
    brand: 'XGIMI',
    name: 'Halo+ (New)',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0D7PKHGWY.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0D7PKHGWY',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '700ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0D7PKHGWY',
    priceJPY: 129800,
    salePriceJPY: 94990,
    discountPercent: 2680,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'xgimi-b0gqxnmg9z',
    brand: 'XGIMI',
    name: 'MoGo 2 Pro (New)',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0GQXNMG9Z.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0GQXNMG9Z',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '430ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0GQXNMG9Z',
    priceJPY: 79800,
    salePriceJPY: 59800,
    discountPercent: 2510,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'xgimi-b0gp7tlz5t',
    brand: 'XGIMI',
    name: 'Elfin Flip Plus',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0GP7TLZ5T.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0GP7TLZ5T',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '500ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0GP7TLZ5T',
    priceJPY: 69800,
    salePriceJPY: 55800,
    discountPercent: 2010,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'xgimi-b0dbqht5m8',
    brand: 'XGIMI',
    name: 'Elfin Flip Pro',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0DBQHT5M8.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0DBQHT5M8',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '400ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'XGIMI OS(迢ｬ閾ｪ)',
    amazonASIN: 'B0DBQHT5M8',
    priceJPY: 69800,
    salePriceJPY: 45800,
    discountPercent: 3440,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'xgimi-b0g8k9trql',
    brand: 'XGIMI',
    name: 'Nova',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0G8K9TRQL.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0G8K9TRQL',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '250ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0G8K9TRQL',
    priceJPY: 39900,
    salePriceJPY: 29900,
    discountPercent: 2510,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'jmgo-b0glzh8z3l',
    brand: 'JMGO',
    name: 'N3 Ultimate',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0GLZH8Z3L.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0GLZH8Z3L',
    resolution: '4K (3840x2160)',
    brightness: '5800ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0GLZH8Z3L',
    priceJPY: 499180,
    salePriceJPY: 399344,
    discountPercent: 2000,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'jmgo-b0dgtj7zj2',
    brand: 'JMGO',
    name: 'N1S Ultimate 4K',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0DGTJ7ZJ2.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0DGTJ7ZJ2',
    resolution: '4K (3840x2160)',
    brightness: '',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0DGTJ7ZJ2',
    priceJPY: 337480,
    salePriceJPY: 226112,
    discountPercent: 3300,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'jmgo-b0d4qlh912',
    brand: 'JMGO',
    name: 'N1S Ultra 4K',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0D4QLH912.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0D4QLH912',
    resolution: '4K (3840x2160)',
    brightness: '',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0D4QLH912',
    priceJPY: 342980,
    salePriceJPY: 210000,
    discountPercent: 3880,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'jmgo-b0dfm3p7xj',
    brand: 'JMGO',
    name: 'N1S Pro 4K',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0DFM3P7XJ.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0DFM3P7XJ',
    resolution: '4K (3840x2160)',
    brightness: '',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0DFM3P7XJ',
    priceJPY: 249480,
    salePriceJPY: 179626,
    discountPercent: 2800,
    isOnPrimeDaySale: false,
    saleType: '繧ｿ繧､繝繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'jmgo-b0f13tn2cp',
    brand: 'JMGO',
    name: 'N1S 4K',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0F13TN2CP.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0F13TN2CP',
    resolution: '4K (3840x2160)',
    brightness: '',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0F13TN2CP',
    priceJPY: 186780,
    salePriceJPY: 118605,
    discountPercent: 3650,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'jmgo-b0d4twcvbb',
    brand: 'JMGO',
    name: 'N1S',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0D4TWCVBB.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0D4TWCVBB',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0D4TWCVBB',
    priceJPY: 149380,
    salePriceJPY: 98591,
    discountPercent: 3400,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'jmgo-b0g1ksz4b8',
    brand: 'JMGO',
    name: 'O2S Ultra 4K',
    type: 'UST',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0G1KSZ4B8.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0G1KSZ4B8',
    resolution: '4K (3840x2160)',
    brightness: '3650ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0G1KSZ4B8',
    priceJPY: 499180,
    salePriceJPY: 399344,
    discountPercent: 2000,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'jmgo-b0gfw17vg4',
    brand: 'JMGO',
    name: 'PicoPlay+',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0GFW17VG4.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0GFW17VG4',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '450ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0GFW17VG4',
    priceJPY: 95260,
    salePriceJPY: 63346,
    discountPercent: 3350,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'anker-b0f3cdq1j1',
    brand: 'ANKER',
    name: 'Nebula X1 + 繧ｵ繝・Λ繧､繝医せ繝斐・繧ｫ繝ｼ繧ｻ繝・ヨ',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0F3CDQ1J1.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0F3CDQ1J1',
    resolution: '4K (3840x2160)',
    brightness: '3500ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0F3CDQ1J1',
    priceJPY: 449900,
    salePriceJPY: 269900,
    discountPercent: 4000,
    isOnPrimeDaySale: false,
    saleType: '繧ｿ繧､繝繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'anker-b0d8hnb8ln',
    brand: 'ANKER',
    name: 'Nebula Cosmos 4K SE',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0D8HNB8LN.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0D8HNB8LN',
    resolution: '4K (3840x2160)',
    brightness: '1800ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝ｬ繝ｼ繧ｶ繝ｼ+LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0D8HNB8LN',
    priceJPY: 199900,
    salePriceJPY: 139900,
    discountPercent: 3000,
    isOnPrimeDaySale: false,
    saleType: '繧ｿ繧､繝繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'anker-b0fscvt4g9',
    brand: 'ANKER',
    name: 'Soundcore Nebula P1',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0FSCVT4G9.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0FSCVT4G9',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '650ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0FSCVT4G9',
    priceJPY: 149900,
    salePriceJPY: 89900,
    discountPercent: 4000,
    isOnPrimeDaySale: false,
    saleType: '繧ｿ繧､繝繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'anker-b0fy2xxwpj',
    brand: 'ANKER',
    name: 'Soundcore Nebula P1i',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0FY2XXWPJ.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0FY2XXWPJ',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '380ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0FY2XXWPJ',
    priceJPY: 49990,
    salePriceJPY: 34990,
    discountPercent: 3000,
    isOnPrimeDaySale: false,
    saleType: '繧ｻ繝ｼ繝ｫ(遞ｮ蛻･陦ｨ險倥↑縺・',
  },
  {
    id: 'anker-b0bctp8vjh',
    brand: 'ANKER',
    name: 'Nebula Capsule 3 Laser',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0BCTP8VJH.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0BCTP8VJH',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '300ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0BCTP8VJH',
    priceJPY: 119900,
    salePriceJPY: 74900,
    discountPercent: 3750,
    isOnPrimeDaySale: false,
    saleType: '繧ｿ繧､繝繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'anker-b0cjdv213w',
    brand: 'ANKER',
    name: 'Nebula Capsule 3',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0CJDV213W.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0CJDV213W',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '200ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0CJDV213W',
    priceJPY: 69990,
    salePriceJPY: 48990,
    discountPercent: 3000,
    isOnPrimeDaySale: false,
    saleType: '繧ｿ繧､繝繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'anker-b0cxtb6cbr',
    brand: 'ANKER',
    name: 'Nebula Capsule Air',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0CXTB6CBR.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0CXTB6CBR',
    resolution: 'HD (1280x720)',
    brightness: '150ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0CXTB6CBR',
    priceJPY: 49990,
    salePriceJPY: 39990,
    discountPercent: 2000,
    isOnPrimeDaySale: false,
    saleType: '繧ｿ繧､繝繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'anker-b0cjdv9f4k',
    brand: 'ANKER',
    name: 'Nebula Mars 3 Air',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0CJDV9F4K.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0CJDV9F4K',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '400ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0CJDV9F4K',
    priceJPY: 89990,
    salePriceJPY: 62990,
    discountPercent: 3000,
    isOnPrimeDaySale: false,
    saleType: '繧ｿ繧､繝繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'epson-b0gnmbyzv5',
    brand: 'EPSON',
    name: 'EF-61WA Lifestudio Pop (Amazon髯仙ｮ・',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0GNMBYZV5.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0GNMBYZV5',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '700繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '3LED(3LCD譁ｹ蠑・',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0GNMBYZV5',
    priceJPY: 90809,
    salePriceJPY: 79980,
    discountPercent: 1190,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'dangbei-b0f7rkfbfy',
    brand: 'Dangbei',
    name: 'DBOX02 Pro',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0F7RKFBFY.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0F7RKFBFY',
    resolution: '4K (3840x2160)',
    brightness: '2000ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝ｬ繝ｼ繧ｶ繝ｼ(LaserVibe)',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0F7RKFBFY',
    priceJPY: 179900,
    salePriceJPY: 136900,
    discountPercent: 2390,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'dangbei-b0d1tyzsxv',
    brand: 'Dangbei',
    name: 'DBOX02',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0D1TYZSXV.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0D1TYZSXV',
    resolution: '4K (3840x2160)',
    brightness: '2450ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝ｬ繝ｼ繧ｶ繝ｼ(ALPD)',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0D1TYZSXV',
    priceJPY: 188900,
    salePriceJPY: 137501,
    discountPercent: 2720,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'dangbei-b0f43ffw3j',
    brand: 'Dangbei',
    name: 'MP1 Max',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0F43FFW3J.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0F43FFW3J',
    resolution: '4K (3840x2160)',
    brightness: '3100ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝ｬ繝ｼ繧ｶ繝ｼ+LED(繝上う繝悶Μ繝・ラ)',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0F43FFW3J',
    priceJPY: 189801,
    salePriceJPY: 180111,
    discountPercent: 510,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'dangbei-b0c5h8vn7r',
    brand: 'Dangbei',
    name: 'DBOX01',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0C5H8VN7R.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0C5H8VN7R',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '2100ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝ｬ繝ｼ繧ｶ繝ｼ(ALPD)',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: '迢ｬ閾ｪOS(Netflix蟇ｾ蠢・',
    amazonASIN: 'B0C5H8VN7R',
    priceJPY: 84800,
    salePriceJPY: 76800,
    discountPercent: 940,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'dangbei-b0dm1qc37p',
    brand: 'Dangbei',
    name: 'Freedo',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0DM1QC37P.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0DM1QC37P',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '450ISO繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0DM1QC37P',
    priceJPY: 68900,
    salePriceJPY: 55900,
    discountPercent: 1890,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'dangbei-b0dzwgpn1l',
    brand: 'Dangbei',
    name: 'N2 mini',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0DZWGPN1L.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0DZWGPN1L',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: '迢ｬ閾ｪOS(Linux繝吶・繧ｹ繝ｻNetflix蜈ｬ蠑・',
    amazonASIN: 'B0DZWGPN1L',
    priceJPY: 29990,
    salePriceJPY: 23990,
    discountPercent: 2000,
    isOnPrimeDaySale: false,
    saleType: '繧ｻ繝ｼ繝ｫ(遞ｮ蛻･陦ｨ險倥↑縺・',
  },
  {
    id: 'aladdin-b0dv49xdd8',
    brand: 'Aladdin',
    name: 'Marca Max',
    type: 'UST',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0DV49XDD8.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0DV49XDD8',
    resolution: '4K (3840x2160)',
    brightness: '2500ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Aladdin OS(迢ｬ閾ｪ)',
    amazonASIN: 'B0DV49XDD8',
    priceJPY: 379800,
    salePriceJPY: 289000,
    discountPercent: 2390,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'aladdin-b0cl8pt7lj',
    brand: 'Aladdin',
    name: 'Marca',
    type: 'UST',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0CL8PT7LJ.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0CL8PT7LJ',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '1000ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝ｬ繝ｼ繧ｶ繝ｼ+LED(繝・Η繧｢繝ｫ蜈画ｺ・',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Aladdin OS(迢ｬ閾ｪ)',
    amazonASIN: 'B0CL8PT7LJ',
    priceJPY: 149800,
    salePriceJPY: 116800,
    discountPercent: 2200,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'aladdin-b0gx5j97yv',
    brand: 'Aladdin',
    name: 'X3',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0GX5J97YV.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0GX5J97YV',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '700ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Aladdin OS(迢ｬ閾ｪ)',
    amazonASIN: 'B0GX5J97YV',
    priceJPY: 99800,
    salePriceJPY: 84900,
    discountPercent: 1490,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'aladdin-b0dcvh2lh6',
    brand: 'Aladdin',
    name: 'X2 Light',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0DCVH2LH6.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0DCVH2LH6',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '700ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Aladdin OS(迢ｬ閾ｪ)',
    amazonASIN: 'B0DCVH2LH6',
    priceJPY: 99800,
    salePriceJPY: 82900,
    discountPercent: 1690,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'aladdin-b0bpbqwbpl',
    brand: 'Aladdin',
    name: 'X2 Plus 謗ｨ螂ｨ繝・Ξ繝薙メ繝･繝ｼ繝翫・繧ｻ繝・ヨ',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0BPBQWBPL.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0BPBQWBPL',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '900ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Aladdin OS(迢ｬ閾ｪ)',
    amazonASIN: 'B0BPBQWBPL',
    priceJPY: 148600,
    salePriceJPY: 123338,
    discountPercent: 1700,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'aladdin-b0fydxn2wc',
    brand: 'Aladdin',
    name: 'Poca Laser',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0FYDXN2WC.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0FYDXN2WC',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '550ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '3濶ｲ繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Aladdin OS(迢ｬ閾ｪ)',
    amazonASIN: 'B0FYDXN2WC',
    priceJPY: 99900,
    salePriceJPY: 76900,
    discountPercent: 2300,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'aladdin-b0fydljbc4',
    brand: 'Aladdin',
    name: 'Poca',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0FYDLJBC4.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0FYDLJBC4',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '450ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Aladdin OS(迢ｬ閾ｪ)',
    amazonASIN: 'B0FYDLJBC4',
    priceJPY: 69900,
    salePriceJPY: 52900,
    discountPercent: 2430,
    isOnPrimeDaySale: false,
    saleType: '繧ｻ繝ｼ繝ｫ(遞ｮ蛻･陦ｨ險倥↑縺・',
  },
  {
    id: 'benq-b0fs1mgct6',
    brand: 'BenQ',
    name: 'TK705i',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0FS1MGCT6.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0FS1MGCT6',
    resolution: '4K (3840x2160)',
    brightness: '3000ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '4LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0FS1MGCT6',
    priceJPY: 229000,
    salePriceJPY: 194650,
    discountPercent: 1500,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'benq-b0dt7x3fkd',
    brand: 'BenQ',
    name: 'GP520',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0DT7X3FKD.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0DT7X3FKD',
    resolution: '4K (3840x2160)',
    brightness: '2600ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0DT7X3FKD',
    priceJPY: 198000,
    salePriceJPY: 168300,
    discountPercent: 1500,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'benq-b0djlvkkbc',
    brand: 'BenQ',
    name: 'GV50',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0DJLVKKBC.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0DJLVKKBC',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '500ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '繝ｬ繝ｼ繧ｶ繝ｼ',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0DJLVKKBC',
    priceJPY: 119800,
    salePriceJPY: 95840,
    discountPercent: 2000,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'benq-b0gc4rkt94',
    brand: 'BenQ',
    name: 'GV32',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0GC4RKT94.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0GC4RKT94',
    resolution: '繝輔ΝHD (1920x1080)',
    brightness: '500ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: 'Google TV',
    amazonASIN: 'B0GC4RKT94',
    priceJPY: 89800,
    salePriceJPY: 71840,
    discountPercent: 2000,
    isOnPrimeDaySale: true,
    saleType: '繝励Λ繧､繝繝・・繧ｻ繝ｼ繝ｫ',
  },
  {
    id: 'benq-b0b969xm54',
    brand: 'BenQ',
    name: 'MW826STH',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 200, h: 150, d: 150 },
    weight: 2,
    imageUrl: '/images/B0B969XM54.jpg',
    websiteUrl: 'https://www.amazon.co.jp/dp/B0B969XM54',
    resolution: 'WXGA (1280x800)',
    brightness: '3500ANSI繝ｫ繝ｼ繝｡繝ｳ',
    lightSource: '豌ｴ驫繝ｩ繝ｳ繝・,
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 200,
    os: '縺ｪ縺・,
    amazonASIN: 'B0B969XM54',
    priceJPY: 99800,
    salePriceJPY: 89820,
    discountPercent: 1000,
    isOnPrimeDaySale: false,
    saleType: '繧ｻ繝ｼ繝ｫ(遞ｮ蛻･陦ｨ險倥↑縺・',
  },
];
