const fs = require('fs');

const file = 'src/types/theater.ts';
let code = fs.readFileSync(file, 'utf8');

const newProjectors = [
  {
    id: 'jmgo-o2s-ultra-4k',
    brand: 'JMGO',
    name: 'O2S Ultra 4K',
    type: 'UST',
    throwRatio: { min: 0.25, max: 0.25 },
    throwDistanceOffset: -100,
    offsetPercent: 120,
    size: { w: 312, h: 142, d: 298 },
    weight: 4.6,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=O2S+Ultra+4K',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+O2S+Ultra+4K',
    resolution: '4K',
    brightness: '2500 ANSI Lumens',
    lightSource: 'Laser',
    projectionMethod: 'DLP',
    minSizeInch: 80,
    maxSizeInch: 120,
    os: 'Android TV'
  },
  {
    id: 'jmgo-n3-ultimate',
    brand: 'JMGO',
    name: 'N3 Ultimate',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 241, h: 236, d: 203 },
    weight: 4.5,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=N3+Ultimate',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+N3+Ultimate',
    resolution: '4K',
    brightness: '3000 ANSI Lumens',
    lightSource: 'Laser',
    projectionMethod: 'DLP',
    minSizeInch: 60,
    maxSizeInch: 150,
    os: 'Google TV'
  },
  {
    id: 'jmgo-n1s-ultimate-4k',
    brand: 'JMGO',
    name: 'N1S Ultimate 4K',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 241, h: 236, d: 203 },
    weight: 4.5,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=N1S+Ultimate+4K',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+N1S+Ultimate+4K',
    resolution: '4K',
    brightness: '3500 ANSI Lumens',
    lightSource: 'Laser',
    projectionMethod: 'DLP',
    minSizeInch: 60,
    maxSizeInch: 150,
    os: 'Android TV'
  },
  {
    id: 'jmgo-n1s-ultra-4k',
    brand: 'JMGO',
    name: 'N1S Ultra 4K',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 241, h: 236, d: 203 },
    weight: 4.5,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=N1S+Ultra+4K',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+N1S+Ultra+4K',
    resolution: '4K',
    brightness: '3000 ANSI Lumens',
    lightSource: 'Laser',
    projectionMethod: 'DLP',
    minSizeInch: 60,
    maxSizeInch: 150,
    os: 'Android TV'
  },
  {
    id: 'jmgo-n1s-pro-4k',
    brand: 'JMGO',
    name: 'N1S Pro 4K',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 241, h: 236, d: 203 },
    weight: 4.5,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=N1S+Pro+4K',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+N1S+Pro+4K',
    resolution: '4K',
    brightness: '2000 ANSI Lumens',
    lightSource: 'Laser',
    projectionMethod: 'DLP',
    minSizeInch: 60,
    maxSizeInch: 150,
    os: 'Android TV'
  },
  {
    id: 'jmgo-n1s-4k',
    brand: 'JMGO',
    name: 'N1S 4K',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 241, h: 236, d: 203 },
    weight: 4.5,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=N1S+4K',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+N1S+4K',
    resolution: '4K',
    brightness: '1500 ANSI Lumens',
    lightSource: 'Laser',
    projectionMethod: 'DLP',
    minSizeInch: 60,
    maxSizeInch: 150,
    os: 'Android TV'
  },
  {
    id: 'jmgo-n1s',
    brand: 'JMGO',
    name: 'N1S',
    type: 'Standard',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 50,
    size: { w: 197, h: 187, d: 167 },
    weight: 2.0,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=N1S',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+N1S',
    resolution: 'Full HD',
    brightness: '900 ANSI Lumens',
    lightSource: 'Laser',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 120,
    os: 'Android TV'
  },
  {
    id: 'jmgo-n1s-nano',
    brand: 'JMGO',
    name: 'N1S Nano',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 100,
    size: { w: 120, h: 120, d: 120 },
    weight: 1.0,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=N1S+Nano',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+N1S+Nano',
    resolution: 'Full HD',
    brightness: '500 ANSI Lumens',
    lightSource: 'Laser',
    projectionMethod: 'DLP',
    minSizeInch: 40,
    maxSizeInch: 100,
    os: 'Android TV'
  },
  {
    id: 'jmgo-picoflix',
    brand: 'JMGO',
    name: 'PicoFlix',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 100,
    size: { w: 100, h: 100, d: 100 },
    weight: 0.8,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=PicoFlix',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+PicoFlix',
    resolution: 'Full HD',
    brightness: '400 ANSI Lumens',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 30,
    maxSizeInch: 100,
    os: 'Android TV'
  },
  {
    id: 'jmgo-picoplay-plus',
    brand: 'JMGO',
    name: 'PicoPlay+',
    type: 'Mobile',
    throwRatio: { min: 1.2, max: 1.2 },
    throwDistanceOffset: 0,
    offsetPercent: 100,
    size: { w: 90, h: 90, d: 90 },
    weight: 0.7,
    imageUrl: 'https://placehold.co/400x300/e2e8f0/1e293b?text=PicoPlay%2B',
    websiteUrl: 'https://www.amazon.co.jp/s?k=JMGO+PicoPlay+',
    resolution: 'Full HD',
    brightness: '300 ANSI Lumens',
    lightSource: 'LED',
    projectionMethod: 'DLP',
    minSizeInch: 30,
    maxSizeInch: 100,
    os: 'Android TV'
  }
];

const insertString = newProjectors.map(p => JSON.stringify(p, null, 2)).join(',\n  ') + '\n];';

code = code.replace(/];/, ',\n  ' + insertString);
fs.writeFileSync(file, code);
